### ISSUE TITLE
Tree gets unbalanced after several glue operations

### ISSUE THREAD

**Issue by reverofevil** [kazu-yamamoto/bst#4]
I took code from [here](https://github.com/kazu-yamamoto/bst/blob/master/Data/SMap/Balance.hs) and called `glue` a few times. Apparently, the tree gets unbalanced after several operations. Am I doing something horribly wrong, or is the implementation incorrect?

https://ideone.com/FCF1OV

**Comment by kazu-yamamoto** [comment]
Do you mean that `balanced` returns `False` for your created tree?

**Comment by polkovnikov-ph** [comment]
Yes, it's in the log for attached code sample. It's enough to `glue` sequentially `singleton k k` for `k` in `[0..7]`.

**Comment by reverofevil** [comment]
Yes, it's in the log for attached code sample. It's enough to `glue` sequentially `singleton k k` for `k` in `[0..7]` for `METHOD=5`:

```
main = putStrLn $ show $ map balanced $ scanl (\t n -> t `glue` singleton n n) Tip [0..7]
```

produces

```
[True,True,True,True,True,True,True,True,False]
```

Given that other operations work correctly, and that this set of parameters [was used](https://hackage.haskell.org/package/order-statistic-tree-0.1.1.1) in the other library without any issues, I suspect there might be something wrong with `glue` specifically, yet I was unable to find what exactly.

**Comment by kazu-yamamoto** [comment]
What I can say is that `glue` MUST be used as in `merge`, only when `isBalanced l r` && `isBalanced r l`. Does your usage satisfy this condition?

**Comment by reverofevil** [comment]
You're right. I'm very sorry about this.
